//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.34209
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppAsignacion.ServicioColaborador {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Colaborador", Namespace="http://schemas.datacontract.org/2004/07/ServicioColaborador.Dominio")]
    [System.SerializableAttribute()]
    public partial class Colaborador : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ApellidosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AreaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CargoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DniField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EstadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FechaIngField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FechaNacField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombresField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Apellidos {
            get {
                return this.ApellidosField;
            }
            set {
                if ((object.ReferenceEquals(this.ApellidosField, value) != true)) {
                    this.ApellidosField = value;
                    this.RaisePropertyChanged("Apellidos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Area {
            get {
                return this.AreaField;
            }
            set {
                if ((object.ReferenceEquals(this.AreaField, value) != true)) {
                    this.AreaField = value;
                    this.RaisePropertyChanged("Area");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Cargo {
            get {
                return this.CargoField;
            }
            set {
                if ((object.ReferenceEquals(this.CargoField, value) != true)) {
                    this.CargoField = value;
                    this.RaisePropertyChanged("Cargo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Dni {
            get {
                return this.DniField;
            }
            set {
                if ((object.ReferenceEquals(this.DniField, value) != true)) {
                    this.DniField = value;
                    this.RaisePropertyChanged("Dni");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Estado {
            get {
                return this.EstadoField;
            }
            set {
                if ((object.ReferenceEquals(this.EstadoField, value) != true)) {
                    this.EstadoField = value;
                    this.RaisePropertyChanged("Estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FechaIng {
            get {
                return this.FechaIngField;
            }
            set {
                if ((object.ReferenceEquals(this.FechaIngField, value) != true)) {
                    this.FechaIngField = value;
                    this.RaisePropertyChanged("FechaIng");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FechaNac {
            get {
                return this.FechaNacField;
            }
            set {
                if ((object.ReferenceEquals(this.FechaNacField, value) != true)) {
                    this.FechaNacField = value;
                    this.RaisePropertyChanged("FechaNac");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombres {
            get {
                return this.NombresField;
            }
            set {
                if ((object.ReferenceEquals(this.NombresField, value) != true)) {
                    this.NombresField = value;
                    this.RaisePropertyChanged("Nombres");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServicioColaborador.IColaboradorService")]
    public interface IColaboradorService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IColaboradorService/ListarColaborador", ReplyAction="http://tempuri.org/IColaboradorService/ListarColaboradorResponse")]
        WebAppAsignacion.ServicioColaborador.Colaborador[] ListarColaborador();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IColaboradorService/ListarColaborador", ReplyAction="http://tempuri.org/IColaboradorService/ListarColaboradorResponse")]
        System.Threading.Tasks.Task<WebAppAsignacion.ServicioColaborador.Colaborador[]> ListarColaboradorAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IColaboradorService/ObtenerColaborador", ReplyAction="http://tempuri.org/IColaboradorService/ObtenerColaboradorResponse")]
        WebAppAsignacion.ServicioColaborador.Colaborador ObtenerColaborador(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IColaboradorService/ObtenerColaborador", ReplyAction="http://tempuri.org/IColaboradorService/ObtenerColaboradorResponse")]
        System.Threading.Tasks.Task<WebAppAsignacion.ServicioColaborador.Colaborador> ObtenerColaboradorAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IColaboradorService/ListarColaboradorXPendiente", ReplyAction="http://tempuri.org/IColaboradorService/ListarColaboradorXPendienteResponse")]
        WebAppAsignacion.ServicioColaborador.Colaborador[] ListarColaboradorXPendiente();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IColaboradorService/ListarColaboradorXPendiente", ReplyAction="http://tempuri.org/IColaboradorService/ListarColaboradorXPendienteResponse")]
        System.Threading.Tasks.Task<WebAppAsignacion.ServicioColaborador.Colaborador[]> ListarColaboradorXPendienteAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IColaboradorServiceChannel : WebAppAsignacion.ServicioColaborador.IColaboradorService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ColaboradorServiceClient : System.ServiceModel.ClientBase<WebAppAsignacion.ServicioColaborador.IColaboradorService>, WebAppAsignacion.ServicioColaborador.IColaboradorService {
        
        public ColaboradorServiceClient() {
        }
        
        public ColaboradorServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ColaboradorServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ColaboradorServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ColaboradorServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public WebAppAsignacion.ServicioColaborador.Colaborador[] ListarColaborador() {
            return base.Channel.ListarColaborador();
        }
        
        public System.Threading.Tasks.Task<WebAppAsignacion.ServicioColaborador.Colaborador[]> ListarColaboradorAsync() {
            return base.Channel.ListarColaboradorAsync();
        }
        
        public WebAppAsignacion.ServicioColaborador.Colaborador ObtenerColaborador(int id) {
            return base.Channel.ObtenerColaborador(id);
        }
        
        public System.Threading.Tasks.Task<WebAppAsignacion.ServicioColaborador.Colaborador> ObtenerColaboradorAsync(int id) {
            return base.Channel.ObtenerColaboradorAsync(id);
        }
        
        public WebAppAsignacion.ServicioColaborador.Colaborador[] ListarColaboradorXPendiente() {
            return base.Channel.ListarColaboradorXPendiente();
        }
        
        public System.Threading.Tasks.Task<WebAppAsignacion.ServicioColaborador.Colaborador[]> ListarColaboradorXPendienteAsync() {
            return base.Channel.ListarColaboradorXPendienteAsync();
        }
    }
}
